// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dandeliondeathray/nona/game (interfaces: Response)

// Package mock is a generated GoMock package.
package mock

import (
	game "github.com/dandeliondeathray/nona/game"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockResponse is a mock of Response interface
type MockResponse struct {
	ctrl     *gomock.Controller
	recorder *MockResponseMockRecorder
}

// MockResponseMockRecorder is the mock recorder for MockResponse
type MockResponseMockRecorder struct {
	mock *MockResponse
}

// NewMockResponse creates a new mock instance
func NewMockResponse(ctrl *gomock.Controller) *MockResponse {
	mock := &MockResponse{ctrl: ctrl}
	mock.recorder = &MockResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockResponse) EXPECT() *MockResponseMockRecorder {
	return m.recorder
}

// OnCorrectWord mocks base method
func (m *MockResponse) OnCorrectWord(arg0 game.Player, arg1 game.Word) {
	m.ctrl.Call(m, "OnCorrectWord", arg0, arg1)
}

// OnCorrectWord indicates an expected call of OnCorrectWord
func (mr *MockResponseMockRecorder) OnCorrectWord(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCorrectWord", reflect.TypeOf((*MockResponse)(nil).OnCorrectWord), arg0, arg1)
}

// OnIncorrectWord mocks base method
func (m *MockResponse) OnIncorrectWord(arg0 game.Player, arg1 game.Word, arg2, arg3 string) {
	m.ctrl.Call(m, "OnIncorrectWord", arg0, arg1, arg2, arg3)
}

// OnIncorrectWord indicates an expected call of OnIncorrectWord
func (mr *MockResponseMockRecorder) OnIncorrectWord(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnIncorrectWord", reflect.TypeOf((*MockResponse)(nil).OnIncorrectWord), arg0, arg1, arg2, arg3)
}

// OnNoRound mocks base method
func (m *MockResponse) OnNoRound(arg0 game.Player) {
	m.ctrl.Call(m, "OnNoRound", arg0)
}

// OnNoRound indicates an expected call of OnNoRound
func (mr *MockResponseMockRecorder) OnNoRound(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnNoRound", reflect.TypeOf((*MockResponse)(nil).OnNoRound), arg0)
}

// OnPerPlayerScores mocks base method
func (m *MockResponse) OnPerPlayerScores(arg0 string, arg1 []game.PerPlayerScore) {
	m.ctrl.Call(m, "OnPerPlayerScores", arg0, arg1)
}

// OnPerPlayerScores indicates an expected call of OnPerPlayerScores
func (mr *MockResponseMockRecorder) OnPerPlayerScores(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPerPlayerScores", reflect.TypeOf((*MockResponse)(nil).OnPerPlayerScores), arg0, arg1)
}

// OnPuzzleNotification mocks base method
func (m *MockResponse) OnPuzzleNotification(arg0 game.Player, arg1 game.Puzzle) {
	m.ctrl.Call(m, "OnPuzzleNotification", arg0, arg1)
}

// OnPuzzleNotification indicates an expected call of OnPuzzleNotification
func (mr *MockResponseMockRecorder) OnPuzzleNotification(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPuzzleNotification", reflect.TypeOf((*MockResponse)(nil).OnPuzzleNotification), arg0, arg1)
}
