apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - name: tcp
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: erikedin/kafka-arm:latest
        command: ["/kafka/bin/zookeeper-server-start.sh"]
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 2181
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 2181
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: zookeeper-config-vol
          mountPath: /config
      volumes:
      - name: zookeeper-config-vol
        configMap:
          name: zookeeper-config