apiVersion: v1
kind: Service
metadata:
  name: kafka-1
spec:
  ports:
    - name: tcp
      port: 9092
      targetPort: 9092
  selector:
    app: kafka-1
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-1-deployment
spec:
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      nodeSelector:
        kubernetes.io/hostname: maia
      containers:
      - name: kafka-1
        image: erikedin/kafka-arm:latest
        command: ["/kafka/bin/kafka-server-start.sh"]
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: kafka-1-config-vol
          mountPath: /config
        - name: data
          mountPath: /data
      volumes:
      - name: kafka-1-config-vol
        configMap:
          name: kafka-1-config
      - name: data
        hostPath:
          path: /kafka