apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: etcd
    etcd_node: etcd0
  name: etcd0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
        etcd_node: etcd0
    spec:
      nodeSelector:
        kubernetes.io/hostname: angela
      containers:
      - command:
        - /usr/local/bin/etcd
        - --name
        - etcd0
        - --data-dir=/data
        - --initial-advertise-peer-urls
        - http://etcd0:2380
        - --listen-peer-urls
        - http://0.0.0.0:2380
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://etcd0:2379
        - --initial-cluster
        - etcd0=http://etcd0:2380
        - --initial-cluster-state
        - new
        image: quay.io/coreos/etcd:v3.2.12
        name: etcd0
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        hostPath:
          path: /etcd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd0
  name: etcd0
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd0